[package]
name = "fetchr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
reqwest = { version = "0.12", features = ["cookies", "json"] }
cookie = "0.17"
tokio = { version = "1", features = ["full"] }
colored = "2.1.0"
serde_json = "1.0.122"
